# Generated by Django 4.0.4 on 2022-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
    ]
